Repository bitcamp-wasd/secret-front, pull requests merged in 2024-06, with the labels that each got.

#1 react initialize
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 🏗️Config

#2 dockerfile config
  dockerfile
Labels: 🏗️Config

#4 반응형 구조를 위해 rem으로 변경 및 메인컨테이너 박스 생성
  .gitignore
  src/components/Footer.jsx
  src/components/Layout.jsx
  src/styles/common.css
  src/styles/components/Banner.css
  src/styles/components/Buttons.css
  src/styles/components/Layout.css
  src/styles/pages/Auth.css
  src/styles/pages/Comments.css
  src/styles/pages/MyPage.css
  src/styles/styles.css
Labels: 🛠FIX, 🏗️Config

#6 태그 컴포넌트 구현
  src/assets/css/index.css
  src/assets/images/tag_drum.svg
  src/assets/images/tag_guitar.svg
  src/assets/images/tag_like.svg
  src/assets/images/tag_piano.svg
  src/assets/images/tag_view.svg
  src/assets/images/tag_violin.svg
  src/components/Tag.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: ✨ FEAT, 🏗️Config

#7 마이페이지-내정보 수정 화면 구현
  src/App.js
  src/assets/css/common.css
  src/assets/css/index.css
  src/components/Banner.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
Labels: ✨ FEAT

#9 동영상 상세보기 화면구현 완성
  src/assets/css/jun.css
  src/assets/css/style.css
  src/assets/images/Sheet_Music.svg
  src/assets/images/grade.svg
  src/assets/images/heart.svg
  src/components/VideoPlay.jsx
  src/pages/Video/PlayVideo.jsx
Labels: ✨ FEAT

#10 메인페이지 화면 구현 및 배너 수정
  src/assets/css/common.css
  src/assets/css/index.css
  src/assets/css/sub.css
  src/assets/images/search.svg
  src/assets/images/upload.svg
  src/components/Tag.jsx
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX, ✨ FEAT

#11 로그인 화면 구현
  src/assets/css/common.css
  src/assets/css/index.css
  src/assets/css/sub.css
  src/assets/images/auth_logo.svg
  src/assets/images/kakao.png
  src/assets/images/naver.svg
  src/pages/Auth/Login.jsx
Labels: ✨ FEAT

#13 회원가입 페이지 화면 구현
  src/assets/css/index.css
  src/assets/css/sub.css
  src/pages/Auth/SignUp.jsx
  src/pages/Video/PlayVideo.jsx
Labels: ✨ FEAT

#17 utyftyf
  src/assets/css/jun.css
  src/components/Tag.jsx
  src/pages/Battle/BattleList.jsx
Labels: ✨ FEAT

#18 댓글페이지 화면구현
  src/assets/css/index.css
  src/assets/css/sub.css
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: ✨ FEAT

#19 마이배틀 화면 구현
  src/App.js
  src/pages/MyPage/MyBettles.jsx
Labels: ✨ FEAT

#20 관리자페이지 화면구현
  src/App.js
  src/assets/css/sub.css
  src/components/Banner_admin.jsx
  src/components/Layout_admin.jsx
  src/pages/MyPage/Administer.jsx
Labels: ✨ FEAT

#22 태그 feat, 메인페이지 feat, 비디오 상세보기 feat
  src/assets/images/heart_fill.svg
  src/components/Tag.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Video/PlayVideo.jsx
Labels: ✨ FEAT

#23 Link와 navigate사용해서 페이지 이동 기능 구현,
  src/App.js
  src/components/Banner.jsx
  src/components/Button.jsx
  src/components/Header.jsx
  src/pages/Auth/Login.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
  src/routes.js
Labels: 🛠FIX, ✨ FEAT

#24 중복되는 라우트 코드 제거
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX

#25 태그버튼 selected가 모두 해제되었을때 전체버튼이 selected로 만듬
  src/components/Tag.jsx
Labels: 🛠FIX

#26 레이아웃 컴포넌트 통일
  src/components/BannerAdmin.jsx
  src/components/BannerBattle.jsx
  src/components/BannerChallenge.jsx
  src/components/BannerMy.jsx
  src/components/Layout.jsx
  src/components/Layout_Ba.jsx
  src/components/Layout_Ch.jsx
  src/components/Layout_admin.jsx
  src/components/Layout_banner_my.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/MyPage/Administer.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyChallenges.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
  src/pages/MyPage/MyLikes.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: 🛠FIX

#27 Update dockerfile
  dockerfile
Labels: 🛠FIX, 🏗️Config

#28 Update dockerfile
  dockerfile
Labels: 🛠FIX

#30 Update README.md
  README.md
Labels: 📜 document

#31 Dev
  README.md
Labels: 📜 document
