Repository bitcamp-wasd/secret-front, pull requests merged in 2024-07, with the labels that each got.

#32 마이페이지 배너,내정보 js구현
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/style.css
  src/assets/css/sub.css
  src/assets/css/yung.css
  src/components/BannerAdmin.jsx
  src/components/BannerBattle.jsx
  src/components/BannerChallenge.jsx
  src/components/BannerMy.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: ✨ FEAT

#34 내 댓글 관련 페이지 삭제 기능 및 더미 데이터 연결
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
Labels: ✨ FEAT

#36 댓글 더미데이터 입출력 구현, register 태그 수정
  package-lock.json
  package.json
  src/components/RegTag.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Video/PlayVideo.jsx
  yarn.lock
Labels: 🛠FIX, ✨ FEAT

#38 좋아요 기능 추가/ 좋아요 애니메이션추가, 배틀리스트 스크롤추가, 배틀리스트 코드 수정, 푸터 mt100추가
  src/assets/css/jun.css
  src/assets/images/battleheart.svg
  src/assets/images/battleheart_fill.svg
  src/components/Footer.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#39 회원가입페이지 js구현
  src/assets/css/index.css
  src/assets/css/sub.css
  src/pages/Auth/SignUp.jsx
Labels: ✨ FEAT

#41 버튼 컴포넌트에서 classname을 받아올 수 있게 수정
  src/components/Button.jsx
  src/components/RegTag.jsx
  src/components/Tag.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🛠FIX

#42 배틀팝업 feat, 마이페이지 스크립트 수정, 배너 수정
  src/assets/css/jun.css
  src/components/BannerBattle.jsx
  src/components/BannerChallenge.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyChallenges.jsx
  src/pages/MyPage/MyLikes.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: 🛠FIX, ✨ FEAT

#43 배너 버튼 css수정, 메인페이지 롤백
  src/assets/css/jun.css
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX

#44 회원가입페이지 연결
  src/pages/Auth/SignUp.jsx
Labels: ✨ FEAT

#45 닉네임 nickNmae : nickname
  src/pages/Auth/SignUp.jsx
Labels: 🛠FIX

#46 로그인 연결
  src/pages/Auth/Login.jsx
Labels: ✨ FEAT

#47 소셜 로그인 구현
  src/pages/Auth/Login.jsx
Labels: ✨ FEAT

#48 로그인 순서 변경 및 로컬스토리지 삭제 임시 기능 구현
  src/assets/css/sub.css
  src/pages/Auth/Login.jsx
Labels: 🛠FIX

#50 소셜로그인 토큰 저장 구현
  src/pages/Auth/Login.jsx
Labels: ✨ FEAT

#51 콜백컴포넌트 생성해서 시도
  src/pages/Auth/OAuthCallback.jsx
  src/routes.js
Labels: 🛠FIX

#52 소셜 로그인 적용
  src/pages/Auth/Login.jsx
Labels: 🛠FIX

#53 공백 alert 기능 구현
  src/pages/Auth/SignUp.jsx
Labels: 🛠FIX

#55 로그아웃 구현
  src/components/Header.jsx
Labels: ✨ FEAT

#56 마이페이지-내정보 차단기능 구현,
  src/components/BannerMy.jsx
  src/components/Header.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: ✨ FEAT

#57 챌린지 배너 오류 수정, Layout 구조 변경, 메인페이지 외 동영상들 반응형 작업, 반응형 헤더 제작
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/images/navmenu.png
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/Tag.jsx
  src/components/VideoBox.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX, ✨ FEAT

#58 헤더 수정, 로그인에서 토큰삭제기능 제거
  src/components/Header.jsx
  src/pages/Auth/Login.jsx
Labels: 🛠FIX

#59 private route 도입
  src/components/Header.jsx
  src/components/PrivateRoute.jsx
  src/pages/Auth/Login.jsx
  src/routes.js
Labels: ✨ FEAT

#60 리다이렉트를 네비게이트로 변경
  src/components/Header.jsx
  src/components/PrivateRoute.jsx
Labels: 🛠FIX

#61 잘못지운 토큰확인 복원
  src/components/Header.jsx
  src/pages/Auth/Login.jsx
Labels: 🛠FIX

#62 라우트 오류 wrap으로 해결시도
  src/components/PrivateRoute.jsx
  src/routes.js
Labels: 🛠FIX

#63 app.js를 참고해서 priavate수정
  src/App.js
  src/components/PrivateRoute.jsx
  src/routes.js
Labels: 🛠FIX

#64 메인페이지 반응형 작업 완료
  src/assets/css/index.css
  src/assets/css/jun.css
  src/components/Tag.jsx
Labels: 🛠FIX

#65 챌린지, 배틀, 메인페이지, 글쓰기 화면 오류 수정, index.css에 videos-flex 수정
  src/assets/css/index.css
  src/components/Layout.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Challenge/ChallengeModify.jsx
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Video/ModifyVideo.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX

#66 myinfo에서 리다이렉트 수정,
  src/components/BannerMy.jsx
  src/components/PrivateRoute.jsx
  src/pages/MyPage/MyInfo.jsx
  src/routes.js
Labels: 🛠FIX

#67 myinfo 백엔드 연결 및 banner,header,signup,login에서 axios URL 수정
  src/components/BannerMy.jsx
  src/components/Header.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🛠FIX, ✨ FEAT

#68 로그인페이지 엔터키 기능 추가, 회원가입 link span 범위 수정
  src/pages/Auth/Login.jsx
Labels: ✨ FEAT

#69 동영상 업로드, 챌린지 업로드 반응형 추가
  src/assets/css/index.css
  src/assets/css/jun.css
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Video/ModifyVideo.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#70 챌린지 상세보기 반응형 완성, 챌린지 리스트 반응형 작업, 비디오 상세보기 반응형 작업 완료
  src/assets/css/index.css
  src/assets/css/jun.css
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#72 내정보 수정하기 연결 완료 및 배너 등급을 span으로 스타일 조정하도록 수정
  src/assets/css/yung.css
  src/components/BannerMy.jsx
  src/pages/MyPage/MyInfoEdit.jsx
Labels: 🛠FIX, ✨ FEAT

#73 Deploy
  package-lock.json
  package.json
  src/App.js
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/style.css
  src/assets/css/sub.css
  src/assets/css/yung.css
  src/assets/images/battleheart.svg
  src/assets/images/battleheart_fill.svg
  src/assets/images/navmenu.png
  src/components/BannerAdmin.jsx
  src/components/BannerBattle.jsx
  src/components/BannerChallenge.jsx
  src/components/BannerMy.jsx
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/PrivateRoute.jsx
  src/components/RegTag.jsx
  src/components/Tag.jsx
  src/components/VideoBox.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/OAuthCallback.jsx
  src/pages/Auth/SignUp.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Challenge/ChallengeModify.jsx
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/Administer.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyChallenges.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
  src/pages/MyPage/MyLikes.jsx
  src/pages/MyPage/MyVideos.jsx
  src/pages/Video/ModifyVideo.jsx
  src/pages/Video/PlayVideo.jsx
  src/pages/Video/RegisterVideo.jsx
  src/routes.js
  src/utils/axiosInstance.js
  yarn.lock
Labels: 🚀deploy

#74 배틀리스트 반응형 작업, 메인페이지 검색기능 추가
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/yung.css
  src/components/BannerBattle.jsx
  src/components/VideoBox_hart.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX, ✨ FEAT

#75 등급 정보 안내 팝업 구현
  src/assets/css/yung.css
  src/assets/images/rank1.svg
  src/assets/images/rank2.svg
  src/assets/images/rank3.svg
  src/assets/images/rank4.svg
  src/assets/images/rank5.svg
  src/components/BannerMy.jsx
  src/pages/MyPage/Rank.jsx
  src/routes.js
Labels: ✨ FEAT

#76 챌린지리스트 수정, 마이페이지 반응형 제작
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/yung.css
  src/components/BannerMy.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: 🛠FIX, ✨ FEAT

#77 동영상 업로드 기능추가 완료
  src/assets/css/jun.css
  src/assets/css/yung.css
  src/components/BannerMy.jsx
  src/components/RegTag.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#78 Update dockerfile
  dockerfile
Labels: 🛠FIX

#79 Dev
  dockerfile
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/yung.css
  src/assets/images/rank1.svg
  src/assets/images/rank2.svg
  src/assets/images/rank3.svg
  src/assets/images/rank4.svg
  src/assets/images/rank5.svg
  src/components/BannerBattle.jsx
  src/components/BannerMy.jsx
  src/components/RegTag.jsx
  src/components/VideoBox_hart.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/Rank.jsx
  src/pages/Video/RegisterVideo.jsx
  src/routes.js
Labels: 🚀deploy

#80 register video
  package-lock.json
  src/components/RegTag.jsx
  src/pages/Video/RegisterVideo.jsx
  yarn.lock
Labels: ✨ FEAT

#82 동영상 등록 페이지 완성
  src/assets/css/jun.css
  src/components/RegTag.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#83 Dev
  src/assets/css/jun.css
  src/components/RegTag.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🚀deploy

#84 비디오 업로드 수정, 메인페이지 콘솔오류 수정, 챌린지리스트 이전챌린지 추가, 배틀상세보기 오류 수정, 헤더 애니메이션추가 …
  src/assets/css/jun.css
  src/components/Header.jsx
  src/components/VideoBox_Ba.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#85 마이페이지-내동영상 연결완료
  src/components/BannerMy.jsx
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: 🛠FIX, ✨ FEAT

#87 콘솔로그 오류메세지 해결
  src/components/VideoBox_Ba.jsx
  src/components/VideoBox_hart.jsx
  src/pages/Auth/Login.jsx
  src/pages/MyPage/Administer.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/MyPage/MyInfo.jsx
Labels: 🛠FIX

#88 메인페이지 연결 및 태그 기능 구현
  src/components/Tag.jsx
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
Labels: ✨ FEAT

#89 터미널 오류메세지 해결, 이전챌린지 드롭다운 애니메이션 추가
  src/assets/css/jun.css
  src/pages/Challenge/ChallengeList.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
Labels: 🛠FIX

#90 헤더 고정, 토글버튼 외부영역 클릭 시 접히게 만듦
  src/assets/css/common.css
  src/assets/css/index.css
  src/components/Header.jsx
Labels: 🛠FIX, ✨ FEAT

#91 폰트변경
  src/assets/css/common.css
  src/assets/css/font.css
  src/assets/css/style.css
  src/assets/images/defaultThumbnail.jpg
  src/components/VideoBox.jsx
  src/index.css
Labels: 🛠FIX

#92 좋아요 체크기능 연결
  src/assets/css/jun.css
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#93 비디오 임시사이즈 제거
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX

#94 폰트두께 100부터 700까지 import
  src/assets/css/common.css
  src/assets/css/font.css
  src/assets/css/yung.css
  src/components/BannerMy.jsx
Labels: 🛠FIX

#95 비디오 업로드 예외처리, 비디오 radius조절,
  src/assets/css/index.css
  src/assets/css/jun.css
  src/components/VideoBox.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#96 로그인,회원가입 디자인 수정
  src/assets/css/index.css
  src/assets/css/sub.css
  src/assets/images/kakao.png
  src/assets/images/kakao.svg
  src/assets/images/main_logo.svg
  src/assets/images/naver.svg
  src/pages/Auth/Login.jsx
  src/pages/Auth/SignUp.jsx
Labels: 🛠FIX

#97 헤더 로고,아이콘 규격,클릭 수정
  src/assets/css/index.css
  src/assets/images/header_mypage.svg
  src/components/Header.jsx
Labels: 🛠FIX

#98 페이지가 이동되면 스크롤을 맨위로 고정시키도록 구현
  src/App.js
  src/components/ScrollToTop.jsx
  src/routes.js
Labels: ✨ FEAT

#99 바디 패딩 헤더에 맞춰서 조절, 업로드 리다이렉트 설정
  src/assets/css/common.css
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#100 닉네임 글자 수 넘어가면 ...으로 바뀜
  src/components/VideoBox.jsx
  src/pages/Challenge/ChallengeList.jsx
Labels: 🛠FIX, ✨ FEAT

#101 스피너 구현 : 마이페이지 배너, 내정보, 내정보 수정
  src/assets/css/index.css
  src/assets/css/yung.css
  src/components/BannerMy.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
Labels: ✨ FEAT

#102 메인페이지에서 동영상 클릭 시 상세보기 페이지로 이동, 닉네임 출력제한 변경
  src/assets/css/jun.css
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Video/PlayVideo.jsx
  src/routes.js
Labels: 🛠FIX, ✨ FEAT

#103 동영상 호버 애니메이션 추가, 콘솔로그 2번찍히는 상황 수정
  src/assets/css/index.css
  src/assets/css/jun.css
  src/components/VideoBox_hart.jsx
  src/index.js
  src/pages/MyPage/MyChallenges.jsx
Labels: 🛠FIX, ✨ FEAT

#104 Feat/connect/main/search
  src/pages/Main/MainPage.jsx
Labels: ✨ FEAT

#105 헤더에서 동일페이지 라우트시 새로고침
  src/components/Header.jsx
Labels: 🛠FIX

#106 닉네임 정규식 프론트,백엔드 적용
  src/pages/Auth/SignUp.jsx
  src/pages/MyPage/MyInfoEdit.jsx
Labels: ✨ FEAT

#107 동영상첨부하기 플레이스홀더 변경
  src/assets/css/jun.css
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#109 클라우드 이미지 연결, 비디오 규격에 썸네일 맞추도록 css수정
  src/assets/css/index.css
  src/components/VideoBox.jsx
Labels: 🛠FIX, ✨ FEAT

#108 네비 위치 수정
  src/assets/css/jun.css
Labels: 🛠FIX, ✨ FEAT

#111 상세보기 경로 수정, 배틀상세보기 투표기능까지 완료
  src/components/VideoBox_Ba.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleList.jsx
  src/routes.js
Labels: 🛠FIX, ✨ FEAT

#112 jwt 디코딩 추가, 마이페이지 라우팅, 관리자페이지 라우팅 구현 완료
  package-lock.json
  package.json
  src/components/AdminRoute.jsx
  src/components/PrivateRoute.jsx
  src/routes.js
  src/utils/jwtUtils.js
  yarn.lock
Labels: ✨ FEAT

#113 내 배틀 연결
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: ✨ FEAT

#114 배틀리스트 댓글 백엔드와 결합
  src/assets/css/jun.css
  src/components/VideoBox_Ba.jsx
  src/components/VideoBox_hart.jsx
  src/components/VideoBox_hart2.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleRegister.jsx
Labels: 🛠FIX, ✨ FEAT

#115 Feat/connect/video cloud
  src/components/VideoPlay.jsx
  src/pages/Video/PlayVideo.jsx
Labels: ✨ FEAT

#116 비디오박스 콘솔로그 오류 해결, 댓글작성, 수정기능까지 추가
  src/components/VideoBox.jsx
  src/pages/Battle/BattleDetail.jsx
Labels: 🛠FIX, ✨ FEAT

#117 댓글삭제기능추가
  package-lock.json
  src/pages/Battle/BattleDetail.jsx
Labels: 🛠FIX, ✨ FEAT

#118 배틀 상세보기 페이지 완료
  src/assets/css/jun.css
  src/pages/Battle/BattleDetail.jsx
Labels: 🛠FIX, ✨ FEAT

#119 배틀상세보기 동영상 클릭 시 새 창 띄우기로 변경
  src/pages/Battle/BattleDetail.jsx
Labels: 🛠FIX

#120 토큰 디코드 검증 주석처리 해제
  src/pages/Battle/BattleDetail.jsx
Labels: 🛠FIX

#121 fetch에서 axios.get으로 변경
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX

#123 배틀 삭제 기능 연결, 배틀등록 예외처리, 배틀리스트 메인페이지 디자인수정
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Main/MainPage.jsx
Labels: 🛠FIX, ✨ FEAT

#124 Dev
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Main/MainPage.jsx
Labels: 🚀deploy

#125 deploy fix
  package-lock.json
Labels: 🚀deploy

#126 Dev
  package-lock.json
Labels: 🚀deploy

#127 yarn install react-scripts
  package.json
  yarn.lock
Labels: 🚀deploy

#128 Dev
  package.json
  yarn.lock
Labels: 🚀deploy

#130 Update dockerfile
  dockerfile
Labels: 🚀deploy

#131 update deploy
  dockerfile
  yarn.lock
Labels: 🚀deploy

#132 Dev
  dockerfile
  yarn.lock
Labels: 🚀deploy

#133 update yarn
  yarn.lock
Labels: 🚀deploy

#134 Dev
  yarn.lock
Labels: 🚀deploy

#135 태그 좋아요 이미지 교체, 간격수정
  src/assets/css/yung.css
  src/assets/images/tag_like.svg
Labels: 🛠FIX

#136 Update dockerfile
  dockerfile
Labels: 🛠FIX, 🚀deploy

#137 index에 공통요소, sub에 특정페이지css 정리 후 yung.css삭제
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/style.css
  src/assets/css/sub.css
  src/assets/css/yung.css
  src/pages/Auth/Login.jsx
Labels: ⚙️ REFACTOR

#138 악보연결 코드 추가
  src/pages/Video/PlayVideo.jsx
Labels: ✨ FEAT

#139 Dev
  src/assets/css/index.css
  src/assets/css/jun.css
  src/assets/css/style.css
  src/assets/css/sub.css
  src/assets/css/yung.css
  src/assets/images/tag_like.svg
  src/pages/Auth/Login.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🚀deploy

#129 비디오 업로드 수정
  src/assets/css/jun.css
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX

#140 영상길이 썸네일 우측하단으로 이동, 메인동영상 스타일 수정, 메인 태그 간격 수정
  src/assets/css/index.css
  src/components/VideoBox.jsx
  src/pages/Main/MainPage.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: 🛠FIX

#142 비디오 등록하기 디자인 수정
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX

#146 로컬스토리지방식에서 세션스토리지방식으로 변경
  src/components/AdminRoute.jsx
  src/components/Header.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/OAuthCallback.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Video/PlayVideo.jsx
  src/pages/Video/RegisterVideo.jsx
  src/utils/axiosInstance.js
  src/utils/jwtUtils.js
Labels: 🛠FIX

#151 애니메이션수정
  src/assets/css/jun.css
  src/components/BannerChallenge.jsx
Labels: 🛠FIX

#152 내댓글 방식변경(전체불러오기->카테고리 불러오기)
  src/assets/css/index.css
  src/assets/css/sub.css
  src/pages/MyPage/MyComments.jsx
Labels: 🛠FIX

#153 콘솔 제거 및 불필요한 주석 제거
  src/components/VideoBox.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/SignUp.jsx
  src/pages/Main/MainPage.jsx
Labels: ⚙️ REFACTOR

#154 동영상 수정하기 연결 완료
  src/pages/Video/ModifyVideo.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#155 동영상 수정하기를 수정함
  src/pages/Video/ModifyVideo.jsx
  src/routes.js
Labels: 🛠FIX

#156 내댓글,삭제 배틀댓글기능 연결
  src/assets/css/jun.css
  src/assets/css/sub.css
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
Labels: ✨ FEAT

#158 동영상 댓글기능(댓글수정추가예정), 배틀 등록 중복불가처리, 댓글삭제 경고처리
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#159 내 댓글 비디오 연결
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyComments.jsx
Labels: ✨ FEAT

#160 동영상 댓글 수정 완료
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#161 Feat/connect/delete comments
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyComments.jsx
Labels: ✨ FEAT

#162 댓글수정하기 ui수정, 배틀 댓글 수정 알럿 추가
  src/pages/Battle/BattleDetail.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#163 Dev
  src/pages/Battle/BattleDetail.jsx
  src/pages/Battle/BattleRegister.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyComments.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🚀deploy

#164 리스트와 등록 각각 따로 포맷팅 함수를 만들어서 설정
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#165 내 정보, 내 게시글 콘솔 제거 및 공백제거
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
  src/pages/MyPage/MyLikes.jsx
  src/pages/MyPage/MyVideos.jsx
Labels: ⚙️ REFACTOR

#166 Dev
  src/pages/MyPage/MyBettles.jsx
  src/pages/MyPage/MyInfo.jsx
  src/pages/MyPage/MyInfoEdit.jsx
  src/pages/MyPage/MyLikes.jsx
  src/pages/MyPage/MyVideos.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🚀deploy

#167 배너 수정, 비디오박스 정보 수정, 지난 챌린지 불러오기 기능 연결
  src/assets/css/jun.css
  src/components/BannerChallenge.jsx
  src/components/VideoBox.jsx
  src/components/VideoBox_Ba.jsx
  src/components/VideoBox_hart.jsx
  src/components/VideoBox_hart2.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeList.jsx
Labels: 🛠FIX, ✨ FEAT

#168 관리자 배너 스타일 변경
  src/assets/css/index.css
  src/assets/images/admin.svg
  src/components/BannerAdmin.jsx
Labels: 🛠FIX

#169 챌린지 리스트 기능 연결
  src/components/VideoBox_best.jsx
  src/components/VideoBox_ch.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Video/RegisterVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#171 챌린지 댓글연결, 좋아요연결, 전체 페이지 불러오는중 -> 스피너로 변경
  src/assets/css/jun.css
  src/components/BannerChallenge.jsx
  src/pages/Battle/BattleList.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#172 리프레시 토큰을 이용해 액세스 토큰 재발급
  src/App.js
  src/components/UseTokenRefresh.jsx
  src/pages/Auth/Login.jsx
  src/utils/axiosInstance.js
Labels: ✨ FEAT

#173 챌린지 카테고리 기능, 챌린지 업로드 수정
  src/assets/css/jun.css
  src/components/Tag.jsx
  src/components/Tagch.jsx
  src/pages/Battle/BattleDetail.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Challenge/ChallengeList.jsx
  src/pages/Challenge/ChallengeRegister.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#174 챌린지 완료(킹경석)
  package-lock.json
  package.json
  src/components/VideoBox.jsx
  src/components/VideoBox_best.jsx
  src/components/VideoBox_ch.jsx
  src/pages/Challenge/ChallengeList.jsx
  yarn.lock
Labels: 🛠FIX, ✨ FEAT

#175 챌린지 투표 확인기능 완료
  src/pages/Challenge/ChallengeDetail.jsx
Labels: 🛠FIX, ✨ FEAT

#177 챌린지 수정삭제버튼 없앰
  src/pages/Challenge/ChallengeDetail.jsx
Labels: 🛠FIX, ✨ FEAT

#178 댓글 최대 글자 수 제한
  src/pages/Battle/BattleDetail.jsx
  src/pages/Challenge/ChallengeDetail.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🛠FIX, ✨ FEAT

#179 Feat/connect/challenge
  src/assets/css/sub.css
  src/components/VideoBox.jsx
  src/pages/MyPage/DeleteComments.jsx
  src/pages/MyPage/MyChallenges.jsx
  src/pages/MyPage/MyComments.jsx
Labels: 🛠FIX, ✨ FEAT

#180 나의 챌린지 연결
  src/pages/MyPage/MyChallenges.jsx
Labels: ✨ FEAT

#183 배틀리스트, 마이배틀 마진 조절
  src/pages/Battle/BattleList.jsx
  src/pages/MyPage/MyBettles.jsx
Labels: 🛠FIX, ✨ FEAT

#184 Dev
  src/pages/Battle/BattleList.jsx
  src/pages/MyPage/MyBettles.jsx
  src/pages/Video/PlayVideo.jsx
Labels: 🚀deploy

#185 내 배틀 시간 포맷
  src/pages/MyPage/MyBettles.jsx
Labels: 🛠FIX

#186 Dev
  src/pages/MyPage/MyBettles.jsx
Labels: 🚀deploy
